# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

#Admin classes
    
    gedmo.listener.sortable:
        class: Gedmo\Sortable\SortableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
            
    admin.facebook_friend:
        class: AppBundle\Admin\FacebookFriendAdmin
        arguments: [~, AppBundle\Entity\FacebookFriend, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: FacebookFriend }

    admin.training:
        class: AppBundle\Admin\TrainingAdmin
        arguments: [~, AppBundle\Entity\Training, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Training }
                        
    admin.sport:
        class: AppBundle\Admin\SportAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: Sport }
        arguments:
            - ~
            - AppBundle\Entity\Sport
            - 'PixSortableBehaviorBundle:SortableAdmin'
            
#Api entrypoint                        
    api_authentication_entry_point:
         class: AppBundle\Entity\Auth\ApiAuthenticationEntryPoint
         arguments: [ api ]

#Oauth user provider for FB LOGIN
    app.provider.oauth:
        class: AppBundle\Entity\Auth\OAuthUserProvider
        arguments: [@fos_user.user_manager,{facebook: facebookUid}]

    app_oauth_server.storage:
        class: AppBundle\Entity\Auth\AppOAuthStorage
        arguments: ["@fos_oauth_server.client_manager", "@fos_oauth_server.access_token_manager", "@fos_oauth_server.refresh_token_manager", "@fos_oauth_server.auth_code_manager", "@?fos_oauth_server.user_provider", "@security.encoder_factory", "@doctrine.orm.entity_manager","@service_container"]

    app_oauth_server.server:
        class: AppBundle\Entity\Auth\AppOAuth2
        arguments: ["@app_oauth_server.storage", "%fos_oauth_server.server.options%"]
